# Gradle properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
version=1.0.0+26.2
maven_group=me.aram
archives_name=smart_copper_golems
enabled_platforms=fabric,neoforge

# Minecraft properties
minecraft_version=26.2

# Dependencies
fabric_loader_version=0.18.6
fabric_api_version=0.152.1+26.2
neoforge_version=26.2.0.0-beta
